theme: jekyll-theme-minimal

└── _site                           # 输出生成文件夹; 网站在此生成
    ├── css
    |   └── style.css               # 页面样式（按原样复制1：1）
    ├── sportdb-update-v192.html    # 博客文章页面
    ├── new-repo-ba-bay.md.html     # 另一个博客网站页面
    ├── sql-views.html              
    ├── new-repo-maps.html          
    ├── quick-starter-datafiles.html    
    ├── feed.xml                    # web订阅源（如atom格式）
    ├── archive.html                # 归档文章
    └── index.html                  # 主页
